DROP TABLE IF EXISTS read_receipts;
DROP TABLE IF EXISTS reactions;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS user_themes;
DROP TABLE IF EXISTS participants;
DROP TABLE IF EXISTS rooms;
DROP TABLE IF EXISTS spaces;
DROP TABLE IF EXISTS users;
