tunnel: b2c6b564-64eb-49a5-ba7d-aa66d4de717b
credentials-file: /etc/cloudflared/b2c6b564-64eb-49a5-ba7d-aa66d4de717b.json

ingress:
  - hostname: fiskos.xyz
    service: http://api:3000
  - hostname: api.fiskos.xyz
    service: http://api:3000
  - hostname: www.fiskos.xyz
    service: http://api:3000
  - service: http_status:404

loglevel: debug
transport-loglevel: debug
